name: terrarium-tests
on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  bats:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Run test stage
        run: |
          docker buildx build \
            --target test \
            --platform linux/amd64 \
            --progress plain \
            -f terraform/docker/Dockerfile.terrarium terraform/docker
